services:
  backendspringboot:
    container_name: backendspringboot
    image: backendspringboot
    networks:
      - shopnet
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shoppingdb
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword

  dbpostgres:
    container_name: dbpostgres
    image: postgres
    networks:
      - shopnet
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: shoppingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  shopnet:
    name: shopnet
